version: "3.7"

services:
  nginx:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./nginx-dev.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    restart: always
    ports:
      - 8000:80
    networks:
      - ngrok-nginx-net

  ngrok:
    container_name: ngrok-container
    image: wernight/ngrok:latest
    # image: wernight/ngrok:armhf # ARM version of the image, use this if running in raspi
    environment:
      NGROK_PORT: nginx:80
    networks:
      - ngrok-nginx-net

networks:
  ngrok-nginx-net: 
    name: ngrok-nginx-net