version: '3.7'

services:
  modbot:
    image: jasoncky96/telegram-modbot:latest
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
    restart: always
    networks:
      - ngrok-nginx-net
      - modbot
    environment:
      NGROK: ngrok-container
      BOT_TOKEN: $BOT_TOKEN
      DEV_CHAT_ID: $DEV_CHAT_ID
      
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_DB: $MONGO_DB
      MONGO_SERVER: db
      MONGO_PORT: 27017    
    depends_on: 
      - db 

  db:
    image: mongo:4.4.9-focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - type: volume
        source: modbot-db
        target: /data/db
    networks:
      - modbot

volumes:
  modbot-db:

networks:
  modbot:
  ngrok-nginx-net:
    external: true