version: '3.7'

services:
  modbot:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: jasoncky96/telegram-modbot:1.0
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    restart: always
    networks:
      - ngrok-nginx-net
      - modbot
    environment:
      NGROK: ngrok-container
      # BOT_TOKEN: $BOT_TOKEN
      BOT_TOKEN: $DEVBOT_TOKEN

      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      
    volumes:
      - type: bind
        source: ./app
        target: /code/app
    depends_on: 
      - db 

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - type: volume
        source: modbot-db
        target: /var/lib/postgresql/data
    networks:
      - modbot

volumes:
  modbot-db:

networks:
  modbot:
  ngrok-nginx-net:
    external: true